### 导入数据

In [1]:
import pandas as pd
import numpy as np

pd.set_option('expand_frame_repr', False)

df = pd.read_csv(filepath_or_buffer='stock_data.csv',
                encoding='gbk',
                 parse_dates=['交易日期']
                )

df = df[['交易日期', '股票代码', '开盘价', '最高价', '最低价', '收盘价', '成交量', '成交额']]
df = df[df['交易日期'] > pd.to_datetime('20171201')]
df = df[df['交易日期'] < pd.to_datetime('20190101')]
df['前收盘价'] = df.groupby('股票代码')['收盘价'].shift(1) 

df.drop(df[np.isnan(df['前收盘价'])].index, inplace=True) # 定位NaN所在的index后删除行
print(df)

             交易日期      股票代码     开盘价     最高价     最低价     收盘价           成交量           成交额    前收盘价
217    2018-01-31  sh600000   12.61   14.00   12.60   13.17  2.529676e+09  3.333193e+10   12.59
218    2018-02-28  sh600000   13.14   13.90   12.24   12.46  1.469635e+09  1.920696e+10   13.17
219    2018-03-30  sh600000   12.40   12.60   11.45   11.65  6.003535e+08  7.307852e+09   12.46
220    2018-04-27  sh600000   11.68   12.02   11.49   11.61  3.847188e+08  4.498217e+09   11.65
221    2018-05-31  sh600000   11.33   11.33   10.39   10.55  5.580226e+08  6.058957e+09   11.61
222    2018-06-29  sh600000   10.60   10.83    9.32    9.56  4.446820e+08  4.475076e+09   10.55
223    2018-07-31  sh600000    9.55   10.20    9.17   10.17  4.329690e+08  4.183506e+09    9.56
224    2018-08-31  sh600000   10.26   10.43    9.66   10.33  4.445087e+08  4.491287e+09   10.17
225    2018-09-28  sh600000   10.27   10.75    9.95   10.62  3.751380e+08  3.864051e+09   10.33
226    2018-10-31  sh600000   10.39   11.12    9.71   10.98  5.646983e+08  5.919033e+09   10.62
227    2018-11-30  sh600000   11.05   11.25   10.43   10.71  4.619115e+08  4.999283e+09   10.98
228    2018-12-28  sh600000   10.99   11.10    9.60    9.80  4.497653e+08  4.701236e+09   10.71
765    2018-01-31  sh600004   14.73   17.00   14.37   16.90  3.880889e+08  6.038348e+09   14.70
766    2018-02-28  sh600004   16.98   17.41   14.00   16.37  2.574015e+08  4.145143e+09   16.90
767    2018-03-30  sh600004   16.30   16.58   14.82   15.64  1.707428e+08  2.697433e+09   16.37
768    2018-04-27  sh600004   15.61   16.40   14.74   15.22  1.537058e+08  2.380246e+09   15.64
769    2018-05-31  sh600004   15.23   16.66   15.04   16.62  2.400207e+08  3.807873e+09   15.22
770    2018-06-29  sh600004   16.52   18.87   12.40   13.09  5.216318e+08  8.081537e+09   16.62
771    2018-07-31  sh600004   13.05   14.84   12.73   13.87  2.785212e+08  3.865052e+09   13.09
772    2018-08-31  sh600004   13.91   14.46   11.85   12.21  2.284297e+08  2.962154e+09   13.87
773    2018-09-28  sh600004   12.11   12.77   11.51   12.77  1.318712e+08  1.598212e+09   12.21
774    2018-10-31  sh600004   12.33   12.54    9.50    9.79  1.954915e+08  2.118601e+09   12.77
775    2018-11-30  sh600004    9.86   10.62    9.73   10.13  2.504056e+08  2.536861e+09    9.79
776    2018-12-28  sh600004   10.28   11.10    9.79   10.05  2.125054e+08  2.224634e+09   10.13
1210   2018-01-31  sh600006    5.86    5.99    5.53    5.57  1.884657e+08  1.091912e+09    5.85
1211   2018-02-28  sh600006    5.55    5.61    4.80    5.17  8.443716e+07  4.331009e+08    5.57
1212   2018-03-30  sh600006    5.15    5.40    4.69    4.92  1.723914e+08  8.876515e+08    5.17
1213   2018-04-27  sh600006    4.92    5.03    4.32    4.33  1.188620e+08  5.608350e+08    4.92
1214   2018-05-31  sh600006    4.38    4.81    4.29    4.36  1.431752e+08  6.546552e+08    4.33
1215   2018-06-29  sh600006    4.36    4.70    3.76    4.09  1.377290e+08  5.771260e+08    4.36
...           ...       ...     ...     ...     ...     ...           ...           ...     ...
489226 2018-12-28  sz300745   35.45   39.90   33.75   36.21  6.154845e+07  2.236961e+09   34.59
489233 2018-06-29  sz300746   13.04   38.38   13.04   34.25  3.182194e+08  1.066815e+10   11.85
489234 2018-07-31  sz300746   35.50   43.45   30.21   30.83  4.586132e+08  1.657483e+10   34.25
489235 2018-08-31  sz300746   31.13   33.27   22.61   22.68  2.207509e+08  5.780452e+09   30.83
489236 2018-09-28  sz300746   22.00   24.80   19.35   19.77  1.246264e+08  2.737679e+09   22.68
489237 2018-10-31  sz300746   18.56   21.20   17.96   20.53  2.874090e+07  5.729100e+08   19.77
489238 2018-11-30  sz300746   20.20   21.00   16.65   17.10  1.202372e+08  2.358993e+09   20.53
489239 2018-12-28  sz300746   17.55   25.19   16.36   18.36  2.325977e+08  4.780000e+09   17.10
489246 2018-07-31  sz300747   88.40  225.00   88.40  181.61  1.234261e+08  2.469530e+10   80.36
489247 2018-08-31  sz300747  182.73  186.50  140.77  161.00  1.173822e+08  1.888731e+10  181.61
489248 2018-09-28  sz300747  160.11  175.50  144.00  158.00  6.153511e+07  9.936883e+09  161.00
489249 2018-10-31  sz300747  153.97  153.97  120.23  132.60  5.455074e+07  7.316935e+09  158.00
489250 2018-11-30  sz300747  133.81  162.95  132.69  139.80  5.073856e+07  7.407337e+09  132.60
489251 2018-12-28  sz300747  145.03  153.78  135.10  137.60  3.403779e+07  4.873028e+09  139.80
489258 2018-10-31  sz300748   12.50   28.82   12.50   27.29  2.242530e+08  5.663041e+09   11.36
489259 2018-11-30  sz300748   30.02   36.32   21.50   22.50  3.180593e+08  8.974308e+09   27.29
489260 2018-12-28  sz300748   23.18   25.86   20.60   21.71  1.927740e+08  4.410467e+09   22.50
489267 2018-10-31  sz300749   25.77   37.66   25.77   29.85  2.039975e+08  6.379940e+09   23.43
489268 2018-11-30  sz300749   29.66   34.77   21.74   23.75  1.754897e+08  4.920084e+09   29.85
489269 2018-12-28  sz300749   24.32   28.95   22.17   22.44  1.062559e+08  2.574119e+09   23.75
489276 2018-07-31  sz300750   70.79   95.08   64.88   72.22  7.426911e+08  5.804075e+10   71.96
489277 2018-08-31  sz300750   72.00   75.66   65.01   65.50  3.175411e+08  2.254465e+10   72.22
489278 2018-09-28  sz300750   64.80   75.09   60.32   73.00  1.944979e+08  1.294626e+10   65.50
489279 2018-10-31  sz300750   71.88   81.58   59.51   74.50  2.318517e+08  1.660830e+10   73.00
489280 2018-11-30  sz300750   75.20   83.80   72.80   80.03  2.138375e+08  1.684157e+10   74.50
489281 2018-12-28  sz300750   82.52   83.49   73.80   73.80  1.469616e+08  1.166667e+10   80.03
489288 2018-12-28  sz300751  130.00  135.40  107.07  119.72  2.926596e+07  3.579443e+09  127.78
489295 2018-12-28  sz300752   33.06   70.87   33.06   56.99  6.727178e+07  4.289582e+09   30.05
489333 2018-11-30  sz300760  100.98  117.00   99.10  112.50  1.911780e+08  2.075754e+10   99.00
489334 2018-12-28  sz300760  115.50  123.66   97.77  109.22  9.502073e+07  1.052038e+10  112.50

[40747 rows x 9 columns]

### 字符串处理

In [4]:
print(df['股票代码'].head())

217    sh600000
218    sh600000
219    sh600000
220    sh600000
221    sh600000
Name: 股票代码, dtype: object

In [6]:
print('sh600000'[:2])

sh

In [7]:
print(df['股票代码'].str[:2])

217       sh
218       sh
219       sh
220       sh
221       sh
222       sh
223       sh
224       sh
225       sh
226       sh
227       sh
228       sh
765       sh
766       sh
767       sh
768       sh
769       sh
770       sh
771       sh
772       sh
773       sh
774       sh
775       sh
776       sh
1210      sh
1211      sh
1212      sh
1213      sh
1214      sh
1215      sh
          ..
489226    sz
489233    sz
489234    sz
489235    sz
489236    sz
489237    sz
489238    sz
489239    sz
489246    sz
489247    sz
489248    sz
489249    sz
489250    sz
489251    sz
489258    sz
489259    sz
489260    sz
489267    sz
489268    sz
489269    sz
489276    sz
489277    sz
489278    sz
489279    sz
489280    sz
489281    sz
489288    sz
489295    sz
489333    sz
489334    sz
Name: 股票代码, Length: 40747, dtype: object

In [11]:
print(df['股票代码'].str.upper().head()) # 全部大写 lower 全部小写

217    SH600000
218    SH600000
219    SH600000
220    SH600000
221    SH600000
Name: 股票代码, dtype: object

In [10]:
print(df['股票代码'].str.len().head()) # 字符串长度

217    8
218    8
219    8
220    8
221    8
Name: 股票代码, dtype: int64

In [13]:
print(df['股票代码'].str.contains('sh')) # 判断是否包含字符串

217        True
218        True
219        True
220        True
221        True
222        True
223        True
224        True
225        True
226        True
227        True
228        True
765        True
766        True
767        True
768        True
769        True
770        True
771        True
772        True
773        True
774        True
775        True
776        True
1210       True
1211       True
1212       True
1213       True
1214       True
1215       True
          ...
489226    False
489233    False
489234    False
489235    False
489236    False
489237    False
489238    False
489239    False
489246    False
489247    False
489248    False
489249    False
489250    False
489251    False
489258    False
489259    False
489260    False
489267    False
489268    False
489269    False
489276    False
489277    False
489278    False
489279    False
489280    False
489281    False
489288    False
489295    False
489333    False
489334    False
Name: 股票代码, Length: 40747, dtype: bool

In [14]:
print(df['股票代码'].str.replace('sz', 'sh'))  # sz替换成sh

217       sh600000
218       sh600000
219       sh600000
220       sh600000
221       sh600000
222       sh600000
223       sh600000
224       sh600000
225       sh600000
226       sh600000
227       sh600000
228       sh600000
765       sh600004
766       sh600004
767       sh600004
768       sh600004
769       sh600004
770       sh600004
771       sh600004
772       sh600004
773       sh600004
774       sh600004
775       sh600004
776       sh600004
1210      sh600006
1211      sh600006
1212      sh600006
1213      sh600006
1214      sh600006
1215      sh600006
            ...
489226    sh300745
489233    sh300746
489234    sh300746
489235    sh300746
489236    sh300746
489237    sh300746
489238    sh300746
489239    sh300746
489246    sh300747
489247    sh300747
489248    sh300747
489249    sh300747
489250    sh300747
489251    sh300747
489258    sh300748
489259    sh300748
489260    sh300748
489267    sh300749
489268    sh300749
489269    sh300749
489276    sh300750
489277    sh300750
489278    sh300750
489279    sh300750
489280    sh300750
489281    sh300750
489288    sh300751
489295    sh300752
489333    sh300760
489334    sh300760
Name: 股票代码, Length: 40747, dtype: object